const URL_EDITOR_OPERATIONS = new Set(['trim', 'params', 'dupes', 'serp', 'hash', 'amp', 'tld']);
const BOT_USER_AGENTS = {
  Googlebot: 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
  Bingbot: 'Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
  Facebook: 'facebookexternalhit/1.1',
  Twitter: 'Twitterbot/1.0',
  Baidu: 'Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/bot.html)',
  Yandex: 'Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)',
  DuckDuckGo: 'DuckDuckBot/1.0; (+http://duckduckgo.com/duckduckbot.html)',
  'GPTBot (OpenAI)': 'Mozilla/5.0 (compatible; GPTBot/1.0; +https://openai.com/gptbot)',
};
const SEARCH_BOTS = ['Googlebot', 'Google Images', 'Google Mobile', 'Google AdsBot', 'Google Media Partners', 'Bingbot', 'DuckDuckBot', 'YandexBot'];
const SOCIAL_BOTS = ['Facebook', 'Instagram', 'WhatsApp', 'Telegram', 'Twitter', 'LinkedIn', 'Pinterest', 'Discord'];
const DUP_RULES = {
  json: ['Block JSON API', '/?rest_route='], search: ['Block Search URLs', '/?s='], params: ['Block Parameters', 'parameters'],
  feed: ['Block Feed URLs', 'etc.'], spam: ['Block Spam Directories', 'etc.'],
};
const WOO_RULES = {
  cart: ['Block Cart Page', '/cart/'], checkout: ['Block Checkout Page', '/checkout/'], account: ['Block My Account', '/my-account/'],
  login: ['Block Login Page', '/login/'], sort: ['Block Sorting Parameters', '&add-to-cart='],
};

function invalid(message) { const error = new Error(message); error.status = 400; throw error; }
function requireText(value, field = 'text') {
  if (typeof value !== 'string') invalid(`${field} is required and must be a string.`);
  return value;
}
function linesFromText(text) { return text.split('\n').map((line) => line.trim()).filter(Boolean); }

export function editUrls(input) {
  const text = requireText(input.text);
  const operation = String(input.operation || input.op || '').trim().toLowerCase();
  if (!URL_EDITOR_OPERATIONS.has(operation)) invalid(`operation must be one of: ${[...URL_EDITOR_OPERATIONS].join(', ')}.`);
  const lines = linesFromText(text);
  let result;
  switch (operation) {
    case 'trim': result = lines.map((url) => { try { return new URL(url).origin; } catch { return url; } }); break;
    case 'params': result = lines.map((url) => url.split('?')[0]); break;
    case 'dupes': result = [...new Set(lines)]; break;
    case 'serp': result = lines.map((url) => url.replace(/[?&](utm_[^=]+|gclid|fbclid)=[^&]*/g, '')); break;
    case 'hash': result = lines.filter((url) => !url.includes('#')); break;
    case 'amp': result = lines.filter((url) => !url.includes('&')); break;
    case 'tld': result = lines.map((url) => { try { return new URL(url).hostname.split('.').slice(-1)[0]; } catch { return url; } }); break;
    default: result = lines;
  }
  return { operation, input: text, result, text: result.join('\n'), inputLineCount: lines.length, outputLineCount: result.length };
}

export function estimateDaPa(input) {
  const text = requireText(input.text);
  const domains = linesFromText(text);
  const results = domains.map((domain) => {
    const host = domain.replace(/^https?:\/\//, '').replace(/^www\./, '').split('/')[0];
    const seed = Array.from(host).reduce((sum, char) => sum + char.charCodeAt(0), 0);
    return { domain: host, da: 10 + (seed % 81), pa: 8 + ((seed * 7) % 83), spam: (seed * 3) % 6 };
  });
  return { results, count: results.length };
}

export function viewAsBot(input) {
  const url = requireText(input.url, 'url');
  if (!url.trim()) invalid('url is required.');
  const bot = String(input.bot || input.selectedBot || 'Googlebot');
  if (!Object.prototype.hasOwnProperty.call(BOT_USER_AGENTS, bot)) invalid('Unsupported bot.');
  return { bot, url, userAgent: BOT_USER_AGENTS[bot], status: 200, title: 'Example Page Title', meta: 'Page meta description as seen by the crawler.' };
}

export function generateRobots(input = {}) {
  const wp = String(input.wp || 'none');
  if (!['none', 'basic', 'advanced'].includes(wp)) invalid('wp must be none, basic, or advanced.');
  const dup = input.dup && typeof input.dup === 'object' ? input.dup : {};
  const woo = input.woo && typeof input.woo === 'object' ? input.woo : {};
  const search = input.search && typeof input.search === 'object' ? input.search : {};
  const social = input.social && typeof input.social === 'object' ? input.social : {};
  const out = ['# robots.txt generated by PGC'];
  if (wp !== 'none') {
    out.push('\n# WordPress defaults', 'User-agent: *', 'Disallow: /wp-admin/', 'Allow: /wp-admin/admin-ajax.php');
    if (wp === 'advanced') out.push('Disallow: /wp-content/plugins/', 'Disallow: /readme.html');
  }
  Object.entries(dup).filter(([, value]) => value).forEach(([key]) => { const rule = DUP_RULES[key]; if (rule) out.push(`\n# ${rule[0]}`, `Disallow: ${rule[1]}`); });
  Object.entries(woo).filter(([, value]) => value).forEach(([key]) => { const rule = WOO_RULES[key]; if (rule) out.push(`\n# ${rule[0]}`, `Disallow: ${rule[1]}`); });
  [...SEARCH_BOTS, ...SOCIAL_BOTS].forEach((bot) => { const value = search[bot] || social[bot]; if (value && value !== 'off') out.push(`\nUser-agent: ${bot}`, `${value === 'allow' ? 'Allow' : 'Disallow'}: /`); });
  if (input.sitemap) out.push(`\nSitemap: ${input.sitemap}`);
  if (input.newsSitemap) out.push(`Sitemap: ${input.newsSitemap}`);
  return { robots: out.join('\n') };
}

export { BOT_USER_AGENTS, SEARCH_BOTS, SOCIAL_BOTS };
