import { useEffect, useMemo, useState } from "react";
import {
  Link2,
  Download,
  Upload,
  Filter,
  RefreshCw,
  ExternalLink,
  AlertTriangle,
  CheckCircle2,
  Sparkles,
  ChevronDown,
} from "lucide-react";
import { useSelectedProjectDomain } from "../../hooks/useSelectedProjectDomain.js";
import { useTechSeoToolResult } from "../../hooks/useTechSeoToolResult.js";
import { downloadTextFile, formatNumber } from "../../lib/techSeoTools.js";
import { analyzeBacklink, DEFAULT_CHECKS, parseBacklinkText } from "../../lib/backlinksAnalyzer.js";
import { buildBacklinksToolResult } from "../../lib/backlinksPersistence.js";

const EMPTY_BACKLINKS_RESULT = buildBacklinksToolResult({});

export default function BacklinksAudit() {
  const { project, projectUrl, displayUrl } = useSelectedProjectDomain();
  const { result: savedResult, saveResult, persistenceError } = useTechSeoToolResult({
    toolKey: "backlinks",
    project,
    projectUrl,
    emptyResult: EMPTY_BACKLINKS_RESULT,
  });
  const [backlinks, setBacklinks] = useState([]);
  const [fileName, setFileName] = useState("No file loaded");
  const [filter, setFilter] = useState("all");
  const [csvFormat, setCsvFormat] = useState("domain");
  const [nicheKeywords, setNicheKeywords] = useState("");
  const [pasteInput, setPasteInput] = useState("");
  const [enabledChecks, setEnabledChecks] = useState(DEFAULT_CHECKS);

  useEffect(() => {
    if (!savedResult || typeof savedResult !== "object") return;
    const nextBacklinks = Array.isArray(savedResult.backlinks) ? savedResult.backlinks : [];
    setBacklinks(nextBacklinks);
    setFileName(savedResult.fileName || "No file loaded");
    setCsvFormat(savedResult.csvFormat || "domain");
    setNicheKeywords(savedResult.nicheKeywords || "");
    setPasteInput(savedResult.pasteInput || "");
    setFilter(savedResult.filter || "all");
    setEnabledChecks(savedResult.enabledChecks && typeof savedResult.enabledChecks === "object" ? { ...DEFAULT_CHECKS, ...savedResult.enabledChecks } : DEFAULT_CHECKS);
  }, [savedResult]);

  const keywords = useMemo(() => nicheKeywords.toLowerCase().split(",").map((item) => item.trim()).filter(Boolean), [nicheKeywords]);
  const analyzedBacklinks = useMemo(() => backlinks.map((link) => analyzeBacklink(link, keywords, enabledChecks)), [backlinks, keywords, enabledChecks]);
  const visibleBacklinks = analyzedBacklinks.filter((link) => {
    if (filter === "all") return true;
    if (filter === "clean") return link.flags.length === 0;
    return link.flags.some((flag) => flag.type === filter || flag.severity === filter);
  });
  const stats = useMemo(() => ({
    total: analyzedBacklinks.length,
    spammy: analyzedBacklinks.filter((link) => link.flags.some((flag) => flag.type === "spammy_tld")).length,
    foreign: analyzedBacklinks.filter((link) => link.flags.some((flag) => flag.type === "foreign")).length,
    adult: analyzedBacklinks.filter((link) => link.flags.some((flag) => flag.type === "adult_gambling")).length,
    irrelevant: analyzedBacklinks.filter((link) => link.flags.some((flag) => flag.type === "irrelevant")).length,
    low: analyzedBacklinks.filter((link) => link.flags.some((flag) => flag.type === "low_quality")).length,
    clean: analyzedBacklinks.filter((link) => link.flags.length === 0).length,
  }), [analyzedBacklinks]);

  async function persistBacklinks(nextBacklinks, nextFileName, nextCsvFormat, nextNicheKeywords, nextPasteInput, nextEnabledChecks, nextFilter) {
    const payload = buildBacklinksToolResult({
      backlinks: nextBacklinks,
      fileName: nextFileName,
      csvFormat: nextCsvFormat,
      nicheKeywords: nextNicheKeywords,
      pasteInput: nextPasteInput,
      enabledChecks: nextEnabledChecks,
      filter: nextFilter,
    });
    await saveResult(payload);
  }

  function loadText(text, nextName = "Pasted CSV") {
    const parsed = parseBacklinkText(text);
    const nextBacklinks = parsed.results;
    const nextCsvFormat = parsed.format;
    setCsvFormat(nextCsvFormat);
    setBacklinks(nextBacklinks);
    setFileName(nextName);
    void persistBacklinks(nextBacklinks, nextName, nextCsvFormat, nicheKeywords, pasteInput, enabledChecks, filter);
  }

  function handleFileUpload(file) {
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (event) => loadText(event.target.result, file.name);
    reader.readAsText(file);
  }

  function exportDisavow() {
    const flagged = analyzedBacklinks.filter((link) => link.flags.length > 0);
    const lines = flagged.map((link) => {
      if (csvFormat === "url" && link.sourceUrl) return link.sourceUrl;
      return `domain:${link.domain}`;
    });
    const content = [
      "# Google Disavow File",
      "# Generated by PGC Backlinks Audit",
      `# Flagged links: ${flagged.length}`,
      `# Date: ${new Date().toISOString().split("T")[0]}`,
      "",
      ...lines,
    ].join("\n");
    downloadTextFile("disavow.txt", content);
  }

  function clearAll() {
    setBacklinks([]);
    setPasteInput("");
    setFileName("No file loaded");
    void persistBacklinks([], "No file loaded", csvFormat, nicheKeywords, "", enabledChecks, filter);
  }

  return (
    <div className="mx-auto max-w-6xl">
      {/* ─── Hero Header ─── */}
      <div className="backlinks-hero">
        <div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between">
          <div className="backlinks-title flex items-center gap-3">
            <Link2 className="h-5 w-5" />
            <div>
              <h1 className="font-display">Backlinks Audit</h1>
              <p className="backlinks-description">Upload Semrush, Ahrefs, or simple backlink CSV/TSV files and generate disavow candidates.</p>
            </div>
          </div>
          <button onClick={exportDisavow} className="ui-button ui-button-primary backlinks-export-button">
            <Download className="h-4 w-4" /> Export Disavow (.txt)
          </button>
        </div>

        {/* Source + target meta row */}
        <div className="backlinks-meta">
          <div className="flex min-w-0 flex-1 items-center gap-2.5">
            <span className="backlinks-meta-label">Target</span>
            <span className="backlinks-meta-value truncate">{displayUrl}</span>
          </div>
          <div className="flex flex-shrink-0 flex-wrap items-center gap-2">
            <span className="backlinks-meta-label">File</span>
            <span className="backlinks-meta-file truncate">{fileName}</span>
            <span className="admin-badge badge-warning">{csvFormat.toUpperCase()} Format</span>
          </div>
        </div>
      </div>

      <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-7">
        <StatPill value={formatNumber(stats.total)} label="Total Links" color="text-blue-400" />
        <StatPill value={stats.spammy} label="Spammy TLDs" color="text-amber-400" />
        <StatPill value={stats.foreign} label="Foreign Lang." color="text-rose-400" />
        <StatPill value={stats.adult} label="Adult/Gambling" color="text-violet-400" />
        <StatPill value={stats.irrelevant} label="Irrelevant" color="text-white/50" />
        <StatPill value={stats.low} label="Low Quality" color="text-orange-400" />
        <StatPill value={stats.clean} label="Clean" color="text-emerald-400" />
      </div>

      <div className="backlinks-panel mt-5">
        <div className="flex flex-wrap items-center gap-3">
          <label className="backlinks-upload">
            <Upload className="h-3.5 w-3.5" /> Upload CSV/TSV
            <input type="file" accept=".csv,.tsv,.txt" className="hidden" onChange={(e) => handleFileUpload(e.target.files?.[0])} />
          </label>
          <FilterSelect value={filter} onChange={setFilter} />
          <button onClick={clearAll} className="backlinks-clear-button">
            <RefreshCw className="h-3.5 w-3.5" /> Clear All
          </button>
        </div>

        {(persistenceError) && <p className="mt-3 text-xs font-semibold text-rose-300">{persistenceError}</p>}

        <div className="mt-3 grid gap-3 lg:grid-cols-[1fr_1fr]">
          <div>
            <label className="backlinks-field-label">Update niche keywords (comma-separated)</label>
            <input
              value={nicheKeywords}
              onChange={(e) => {
                const nextValue = e.target.value;
                setNicheKeywords(nextValue);
                void persistBacklinks(backlinks, fileName, csvFormat, nextValue, pasteInput, enabledChecks, filter);
              }}
              className="backlinks-input mt-1.5 w-full"
              placeholder="SEO, marketing, web design"
            />
          </div>
          <div>
            <label className="backlinks-field-label">Paste CSV/TSV export</label>
            <div className="mt-1 flex gap-2">
              <textarea value={pasteInput} onChange={(e) => {
                const nextValue = e.target.value;
                setPasteInput(nextValue);
                void persistBacklinks(backlinks, fileName, csvFormat, nicheKeywords, nextValue, enabledChecks, filter);
              }} rows={2} className="backlinks-input flex-1" placeholder="Domain,DR,Backlinks,Country..." />
              <button onClick={() => loadText(pasteInput)} className="ui-button backlinks-analyze-button">Analyze</button>
            </div>
          </div>
        </div>

        <div className="mt-3 flex flex-wrap gap-3">
          {Object.entries(enabledChecks).map(([key, value]) => (
            <label key={key} className="backlinks-check">
              <input type="checkbox" checked={value} onChange={(e) => {
                const nextEnabledChecks = { ...enabledChecks, [key]: e.target.checked };
                setEnabledChecks(nextEnabledChecks);
                void persistBacklinks(backlinks, fileName, csvFormat, nicheKeywords, pasteInput, nextEnabledChecks, filter);
              }} className="h-3.5 w-3.5" />
              {key.replace(/_/g, " ")}
            </label>
          ))}
        </div>
      </div>

      <div className="mt-5 flex items-center gap-2">
        <Filter className="h-4 w-4 text-white/30" />
        <span className="text-sm font-bold text-white/70">Audit Checks</span>
        <span className="rounded-full bg-violet-500/15 px-2 py-0.5 text-[10px] font-bold text-violet-300">{visibleBacklinks.length} shown</span>
      </div>

      <div className="mt-3 overflow-hidden rounded-2xl border border-white/[0.06] bg-white/[0.02]">
        <div className="grid grid-cols-[2fr_0.5fr_0.6fr_0.5fr_1.1fr_0.6fr] gap-3 border-b border-white/[0.06] px-5 py-3">
          <TableHead label="Domain" />
          <TableHead label="AS/DR" />
          <TableHead label="Country" />
          <TableHead label="Links" />
          <TableHead label="Issues" />
          <TableHead label="Actions" align="right" />
        </div>
        {visibleBacklinks.length ? visibleBacklinks.map((row, i) => (
          <div key={`${row.domain}-${i}`} className={`grid grid-cols-[2fr_0.5fr_0.6fr_0.5fr_1.1fr_0.6fr] gap-3 px-5 py-3 transition hover:bg-white/[0.02] ${i < visibleBacklinks.length - 1 ? "border-b border-white/[0.03]" : ""}`}>
            <div className="min-w-0">
              <div className="flex items-center gap-2">
                <div className="flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-lg bg-white/[0.06] text-[10px] font-bold text-white/40">{row.domain.slice(0, 2).toUpperCase()}</div>
                <div className="min-w-0">
                  <div className="truncate text-sm font-semibold text-white/85">{row.domain}</div>
                  <div className="truncate text-[10px] text-white/30">{row.tld} {row.traffic ? `- ${formatNumber(row.traffic)} traffic` : ""}</div>
                </div>
              </div>
            </div>
            <div className="flex items-center text-sm font-bold text-white/80">{row.dr}</div>
            <div className="flex items-center text-xs text-white/50">{row.country || "-"}</div>
            <div className="flex items-center text-xs text-white/70">{formatNumber(row.backlinks)}</div>
            <div className="flex flex-wrap items-center gap-1">
              {row.flags.length === 0 ? (
                <span className="flex items-center gap-1 text-xs text-emerald-400"><CheckCircle2 className="h-3 w-3" /> Clean</span>
              ) : row.flags.slice(0, 3).map((flag) => (
                <span key={`${flag.type}-${flag.message}`} className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${flag.severity === "critical" ? "bg-rose-500/20 text-rose-300" : flag.severity === "high" ? "bg-orange-500/20 text-orange-300" : "bg-amber-500/15 text-amber-300"}`}>
                  {flag.message}
                </span>
              ))}
            </div>
            <div className="flex items-center justify-end">
              <a href={row.sourceUrl || row.url} target="_blank" rel="noopener noreferrer" className="flex items-center gap-1 rounded-lg border border-white/10 bg-white/[0.03] px-2.5 py-1 text-[10px] text-white/50 hover:bg-white/[0.06]">
                <ExternalLink className="h-3 w-3" /> Visit
              </a>
            </div>
          </div>
        )) : (
          <div className="px-5 py-10 text-center text-sm text-white/30">Upload or paste a backlink export to begin.</div>
        )}
      </div>
    </div>
  );
}

function FilterSelect({ value, onChange }) {
  return (
    <div className="flex items-center gap-1.5 rounded-lg border border-white/10 bg-ink-900/60 px-3 py-1.5">
      <Filter className="h-3 w-3 text-white/30" />
      <select value={value} onChange={(e) => onChange(e.target.value)} className="appearance-none bg-transparent text-[11px] text-white/60 focus:outline-none">
        <option value="all">All Backlinks</option>
        <option value="clean">Clean</option>
        <option value="critical">Critical</option>
        <option value="high">High</option>
        <option value="spammy_tld">Spammy TLD</option>
        <option value="foreign">Foreign</option>
        <option value="adult_gambling">Adult/Gambling</option>
        <option value="low_quality">Low Quality</option>
        <option value="irrelevant">Irrelevant</option>
      </select>
      <ChevronDown className="h-3 w-3 text-white/30" />
    </div>
  );
}

function StatPill({ value, label, color }) {
  return (
    <div className="backlinks-stat">
      <div className="backlinks-stat-label">{label}</div>
      <div className={`backlinks-stat-value ${color}`}>{value}</div>
    </div>
  );
}

function TableHead({ label, align = "left" }) {
  return <span className={`text-[10px] font-bold uppercase tracking-wider text-white/30 ${align === "right" ? "text-right" : ""}`}>{label}</span>;
}
