import { useState } from "react";
import { FileCode2, Shield, ChevronDown, Globe, Lightbulb, Copy, Download, Search, Share2 } from "lucide-react";
import ToolHeader from "../../components/seotools/ToolHeader.jsx";

const wpDefaults = [
  { label: "None", value: "none" },
  { label: "Basic", value: "basic" },
  { label: "Advanced", value: "advanced" },
];

const dupRules = [
  { key: "json", title: "Block JSON API", desc: "Block /wp-json/ and /?rest_route=" },
  { key: "search", title: "Block Search URLs", desc: "Block /search/ and /?s=" },
  { key: "params", title: "Block Parameters", desc: "Block ?s=, ?p=, &preview= parameters" },
  { key: "feed", title: "Block Feed URLs", desc: "Block /feed/, /comments/feed, etc." },
  { key: "spam", title: "Block Spam Directories", desc: "Block /trackback/, /wp-comments, etc." },
];

const wooRules = [
  { key: "cart", title: "Block Cart Page", desc: "Block /cart/" },
  { key: "checkout", title: "Block Checkout Page", desc: "Block /checkout/" },
  { key: "account", title: "Block My Account", desc: "Block /my-account/" },
  { key: "login", title: "Block Login Page", desc: "Block /login/" },
  { key: "sort", title: "Block Sorting Parameters", desc: "Block ?orderby=, ?filter=, ?add-to-cart=" },
];

const searchBots = ["Googlebot", "Google Images", "Google Mobile", "Google AdsBot", "Google Media Partners", "Bingbot", "DuckDuckBot", "YandexBot"];
const socialBots = ["Facebook", "Instagram", "WhatsApp", "Telegram", "Twitter", "LinkedIn", "Pinterest", "Discord"];

export default function RobotsGenerator() {
  const [wp, setWp] = useState("none");
  const [dup, setDup] = useState({});
  const [woo, setWoo] = useState({});
  const [search, setSearch] = useState({});
  const [social, setSocial] = useState({});
  const [sitemap, setSitemap] = useState("");
  const [newsSitemap, setNewsSitemap] = useState("");
  const [open, setOpen] = useState({ wp: true, dup: true, woo: true, sitemap: true, search: true, social: true });

  function generate() {
    let out = ["# robots.txt generated by PGC"];
    if (wp !== "none") {
      out.push("\n# WordPress defaults");
      out.push("User-agent: *");
      out.push("Disallow: /wp-admin/");
      out.push("Allow: /wp-admin/admin-ajax.php");
      if (wp === "advanced") {
        out.push("Disallow: /wp-content/plugins/");
        out.push("Disallow: /readme.html");
      }
    }
    Object.entries(dup).filter(([_, v]) => v).forEach(([k]) => {
      const rule = dupRules.find((r) => r.key === k);
      out.push(`\n# ${rule.title}`);
      out.push(`Disallow: ${rule.desc.split(" ").pop()}`);
    });
    Object.entries(woo).filter(([_, v]) => v).forEach(([k]) => {
      const rule = wooRules.find((r) => r.key === k);
      out.push(`\n# ${rule.title}`);
      out.push(`Disallow: ${rule.desc.split(" ").pop()}`);
    });
    [...searchBots, ...socialBots].forEach((bot) => {
      const v = search[bot] || social[bot];
      if (v && v !== "off") {
        out.push(`\nUser-agent: ${bot}`);
        out.push(`${v === "allow" ? "Allow" : "Disallow"}: /`);
      }
    });
    if (sitemap) out.push(`\nSitemap: ${sitemap}`);
    if (newsSitemap) out.push(`Sitemap: ${newsSitemap}`);
    return out.join("\n");
  }

  const preview = generate() || `# Your robots.txt will appear here\n# Start by selecting options on the left`;

  const Section = ({ id, icon: Icon, title, desc, children, color = "violet" }) => (
    <div className="rounded-2xl border border-white/[0.08] bg-[#0d1117] overflow-hidden">
      <button onClick={() => setOpen({ ...open, [id]: !open[id] })} className="flex w-full items-center justify-between p-4">
        <div className="flex items-center gap-2.5">
          <Icon className={`h-4 w-4 text-${color}-400`} />
          <div className="text-left">
            <h3 className="text-sm font-bold text-white/80">{title}</h3>
            {desc && <p className="text-[11px] text-white/35 mt-0.5">{desc}</p>}
          </div>
        </div>
        <ChevronDown className={`h-4 w-4 text-white/30 transition-transform ${open[id] ? "rotate-180" : ""}`} />
      </button>
      {open[id] && <div className="border-t border-white/[0.06] p-4 space-y-2">{children}</div>}
    </div>
  );

  const Toggle = ({ checked, onChange }) => (
    <button
      onClick={() => onChange(!checked)}
      className={`relative h-5 w-9 rounded-full transition ${checked ? "bg-indigo-600" : "bg-white/10"}`}
    >
      <span className={`absolute top-0.5 h-4 w-4 rounded-full bg-white transition ${checked ? "left-4" : "left-0.5"}`} />
    </button>
  );

  const RuleRow = ({ title, desc, checked, onChange }) => (
    <div className="flex items-center justify-between rounded-lg border border-white/[0.06] bg-[#010409] px-3 py-2.5">
      <div>
        <p className="text-xs font-semibold text-white/70">{title}</p>
        <p className="text-[10px] text-white/35">{desc}</p>
      </div>
      <Toggle checked={checked} onChange={onChange} />
    </div>
  );

  const BotRow = ({ name, value, onChange }) => (
    <div className="flex items-center justify-between rounded-lg border border-white/[0.06] bg-[#010409] px-3 py-2.5">
      <span className="text-xs font-semibold text-white/70">{name}</span>
      <div className="flex items-center gap-1 rounded-md bg-white/[0.03] p-0.5">
        {["allow", "disallow", "off"].map((v) => (
          <button
            key={v}
            onClick={() => onChange(v)}
            className={`rounded px-2 py-0.5 text-[10px] font-bold capitalize transition ${
              (value || "off") === v ? "bg-white/15 text-white" : "text-white/35 hover:text-white/55"
            }`}
          >{v}</button>
        ))}
      </div>
    </div>
  );

  return (
    <div className="mx-auto max-w-6xl space-y-4">
      <ToolHeader title="Robots.txt Generator" Icon={FileCode2} gradient="from-slate-800 via-indigo-800 to-violet-700" subtitle="Create an optimized robots.txt file for your website" />

      <div className="grid gap-4 lg:grid-cols-[1fr_420px]">
        {/* Left column */}
        <div className="space-y-3">
          <div className="rounded-2xl border border-white/[0.08] bg-[#0d1117] p-5">
            <h2 className="font-display text-lg font-black text-white">Robots.txt Generator</h2>
            <p className="text-xs text-white/40 mt-0.5">Create an optimized robots.txt file for your website</p>
            <button className="mt-3 flex items-center gap-1.5 rounded-lg bg-gradient-to-r from-indigo-600 to-violet-600 px-4 py-2 text-xs font-bold text-white shadow-md shadow-indigo-600/20">
              <Shield className="h-3.5 w-3.5" /> Generate Recommended
            </button>
          </div>

          <Section id="wp" icon={Globe} title="WordPress Defaults" desc="Protect your WordPress backend and allow essential resources." color="indigo">
            <div className="flex gap-2">
              {wpDefaults.map((d) => (
                <button
                  key={d.value}
                  onClick={() => setWp(d.value)}
                  className={`flex-1 rounded-lg px-3 py-2 text-xs font-bold transition ${
                    wp === d.value ? "bg-gradient-to-r from-indigo-600 to-violet-600 text-white" : "border border-white/[0.08] bg-white/[0.03] text-white/55 hover:text-white/80"
                  }`}
                >{d.label}</button>
              ))}
            </div>
          </Section>

          <Section id="dup" icon={Shield} title="Block Duplicate Content" desc="Prevent crawling of URLs that create duplicate content issues." color="violet">
            {dupRules.map((r) => (
              <RuleRow key={r.key} {...r} checked={!!dup[r.key]} onChange={(v) => setDup({ ...dup, [r.key]: v })} />
            ))}
          </Section>

          <Section id="woo" icon={Shield} title="WooCommerce Optimization" desc="Block non-indexable WooCommerce pages and parameters." color="emerald">
            {wooRules.map((r) => (
              <RuleRow key={r.key} {...r} checked={!!woo[r.key]} onChange={(v) => setWoo({ ...woo, [r.key]: v })} />
            ))}
          </Section>

          <Section id="sitemap" icon={FileCode2} title="Add Sitemaps" desc="Add your sitemap URLs to help search engines discover your content." color="cyan">
            <label className="text-[10px] font-bold uppercase tracking-wider text-white/40">Sitemap URLs</label>
            <input value={sitemap} onChange={(e) => setSitemap(e.target.value)} className="mt-1 w-full rounded-lg border border-white/[0.06] bg-[#010409] px-3 py-2 text-sm text-white/60 placeholder:text-white/20 focus:outline-none" placeholder="https://example.com/sitemap.xml" />
            <label className="text-[10px] font-bold uppercase tracking-wider text-white/40 mt-2 block">News Sitemap URL (optional)</label>
            <input value={newsSitemap} onChange={(e) => setNewsSitemap(e.target.value)} className="mt-1 w-full rounded-lg border border-white/[0.06] bg-[#010409] px-3 py-2 text-sm text-white/60 placeholder:text-white/20 focus:outline-none" placeholder="https://example.com/sitemap-news.xml" />
          </Section>

          <Section id="search" icon={Search} title="Search Engine Crawlers" desc="Control which search engines can crawl your website." color="blue">
            {searchBots.map((b) => (
              <BotRow key={b} name={b} value={search[b]} onChange={(v) => setSearch({ ...search, [b]: v })} />
            ))}
          </Section>

          <Section id="social" icon={Share2} title="Social Media Crawlers" desc="Control social media platform crawlers for link previews." color="fuchsia">
            {socialBots.map((b) => (
              <BotRow key={b} name={b} value={social[b]} onChange={(v) => setSocial({ ...social, [b]: v })} />
            ))}
          </Section>
        </div>

        {/* Right column - Sticky Preview */}
        <div className="space-y-3 lg:sticky lg:top-4 lg:self-start">
          <div className="rounded-2xl border border-white/[0.08] bg-[#0d1117] overflow-hidden">
            <div className="flex items-center justify-between border-b border-white/[0.06] px-4 py-3">
              <div className="flex items-center gap-2">
                <FileCode2 className="h-4 w-4 text-indigo-400" />
                <span className="text-sm font-bold text-white/80">robots.txt Preview</span>
              </div>
              <div className="flex gap-1.5">
                <button onClick={() => navigator.clipboard.writeText(preview)} className="flex items-center gap-1 rounded-md bg-gradient-to-r from-indigo-600 to-violet-600 px-2.5 py-1 text-[10px] font-bold text-white">
                  <Copy className="h-3 w-3" /> Copy
                </button>
                <button className="flex items-center gap-1 rounded-md border border-white/[0.08] bg-white/[0.03] px-2.5 py-1 text-[10px] font-bold text-white/55">
                  <Download className="h-3 w-3" /> Download
                </button>
              </div>
            </div>
            <pre className="max-h-[300px] overflow-y-auto bg-black/40 p-4 text-[11px] text-cyan-200/80 font-mono whitespace-pre-wrap">{preview}</pre>
          </div>

          <div className="rounded-2xl border border-indigo-500/20 bg-indigo-500/[0.04] p-4">
            <h4 className="flex items-center gap-1.5 text-sm font-bold text-indigo-300 mb-2">
              <Lightbulb className="h-4 w-4" /> Quick Tips
            </h4>
            <ul className="space-y-1 text-[11px] text-white/50">
              <li>• Place robots.txt in your website root directory</li>
              <li>• Test with Google Search Console before deploying</li>
              <li>• Remember: robots.txt is a suggestion, not a security measure</li>
              <li>• Blocking crawlers won't remove already-indexed pages</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
